export const OVERSCAN_DEFAULT = 5;

export const ESTIMATED_CARD_HEIGHT_BANK = 220;
export const ESTIMATED_CARD_HEIGHT_KANBAN = 168;
export const ESTIMATED_CARD_HEIGHT_OPPORTUNITY_ROW = 220;
export const ESTIMATED_CARD_HEIGHT_ANSWER = 240;
export const ESTIMATED_CARD_HEIGHT_DRAFT = 132;
export const ESTIMATED_CARD_HEIGHT_SEND = 124;

export const BANK_GRID_GAP_PX = 12;
export const MIN_BANK_COLUMN_WIDTH_PX = 280;
export const MIN_ANSWER_COLUMN_WIDTH_PX = 360;
