/**
 * @route POST /api/ats/scans
 * @route GET /api/ats/scans
 * @description POST: Persist a scan generated by the in-app /ats page.
 *   GET: Fetch the user's scan history for the /ats page list.
 * @auth Required
 *
 * The existing `/api/ats/scan` route is profile-driven — it loads the
 * server-side stored profile + a `jobId` and regenerates the report.
 * `/ats` runs the scan entirely client-side via `<ScannerForm>` and
 * persists the result here.
 */
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import {
  getScanHistory,
  saveInAppScan,
  type InAppScanSavePayload,
} from "@/lib/db/ats-scans";
import { requireAuth, isAuthError } from "@/lib/auth";

export const dynamic = "force-dynamic";

// We accept the full ATSScanResult as opaque JSON — the shape is wide
// (axes, content checks, pdf layout, etc.) and the route does not need
// to introspect it beyond the score fields validated below.
const scanResultSchema = z
  .object({
    overall: z.number().min(0).max(100),
    letterGrade: z.string().min(1).max(2),
    axes: z.record(z.string(), z.unknown()),
    issues: z.array(z.unknown()),
    keywords: z.array(z.unknown()),
    summary: z.string(),
    recommendations: z.array(z.string()),
    scannedAt: z.string(),
    legacy: z.object({
      score: z.object({
        overall: z.number(),
        formatting: z.number(),
        keywords: z.number(),
        content: z.number(),
        structure: z.number(),
      }),
      issues: z.array(z.unknown()),
      keywords: z.array(z.unknown()),
      summary: z.string(),
      recommendations: z.array(z.string()),
    }),
  })
  .passthrough();

const saveSchema = z.object({
  result: scanResultSchema,
  jobLabel: z.string().trim().max(200).optional(),
  jobTitle: z.string().trim().max(200).optional(),
  jobCompany: z.string().trim().max(200).optional(),
  opportunityId: z.string().trim().max(64).optional(),
  jdText: z.string().max(50_000).optional(),
});

export async function POST(request: NextRequest) {
  const authResult = await requireAuth();
  if (isAuthError(authResult)) return authResult;

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const parsed = saveSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { error: "Validation failed", details: parsed.error.flatten() },
      { status: 400 },
    );
  }

  try {
    // Cast to the lib's payload type — zod gives us a structurally
    // compatible shape but the `result` field is intentionally opaque.
    const id = saveInAppScan(
      authResult.userId,
      parsed.data as unknown as InAppScanSavePayload,
    );
    return NextResponse.json({ id }, { status: 201 });
  } catch (error) {
    if (error instanceof Error && error.message === "Opportunity not found") {
      return NextResponse.json(
        { error: "Opportunity not found" },
        { status: 404 },
      );
    }
    console.error("Save in-app ATS scan error:", error);
    return NextResponse.json({ error: "Failed to save scan" }, { status: 500 });
  }
}

export async function GET(request: NextRequest) {
  const authResult = await requireAuth();
  if (isAuthError(authResult)) return authResult;

  try {
    const { searchParams } = new URL(request.url);
    const rawLimit = parseInt(searchParams.get("limit") || "20", 10);
    const limit = Math.min(
      Number.isFinite(rawLimit) && rawLimit > 0 ? rawLimit : 20,
      100,
    );

    const history = getScanHistory(authResult.userId, limit);
    return NextResponse.json({ history });
  } catch (error) {
    console.error("List in-app ATS scans error:", error);
    return NextResponse.json(
      { error: "Failed to fetch scan history" },
      { status: 500 },
    );
  }
}
