import type { ThemePreset } from "../tokens";
import { createThemeTokens, sansFont, sharedStatusTokens } from "./shared";

const id = "minimal";
const name = "Minimal";
const description = "Quiet monochrome surfaces with thin borders and restrained depth.";

export const minimalTheme = {
  id,
  name,
  description,
  preview: {
    primary: "#222222",
    background: "#fafafa",
    accent: "#dddddd",
  },
  light: createThemeTokens(id, name, description, {
    background: "0 0% 98%",
    foreground: "0 0% 13%",
    card: "0 0% 100%",
    cardForeground: "0 0% 13%",
    popover: "0 0% 100%",
    popoverForeground: "0 0% 13%",
    primary: "0 0% 13%",
    primaryForeground: "0 0% 100%",
    secondary: "0 0% 94%",
    secondaryForeground: "0 0% 13%",
    muted: "0 0% 96%",
    mutedForeground: "0 0% 60%",
    accent: "0 0% 87%",
    accentForeground: "0 0% 13%",
    border: "0 0% 90%",
    input: "0 0% 87%",
    ring: "0 0% 13%",
    ...sharedStatusTokens,
    radius: "0.5rem",
    shadowCard: "none",
    shadowElevated: "0 8px 24px rgba(0,0,0,0.06)",
    shadowButton: "none",
    fontFamily: sansFont,
    fontHeading: sansFont,
    letterSpacing: "0",
    textTransform: "none",
    fontWeightNormal: "400",
    fontWeightMedium: "500",
    fontWeightBold: "600",
    borderWidth: "1px",
  }),
  dark: createThemeTokens(id, name, description, {
    background: "0 0% 8%",
    foreground: "0 0% 80%",
    card: "0 0% 11%",
    cardForeground: "0 0% 87%",
    popover: "0 0% 11%",
    popoverForeground: "0 0% 87%",
    primary: "0 0% 87%",
    primaryForeground: "0 0% 7%",
    secondary: "0 0% 16%",
    secondaryForeground: "0 0% 87%",
    muted: "0 0% 16%",
    mutedForeground: "0 0% 33%",
    accent: "0 0% 87%",
    accentForeground: "0 0% 7%",
    border: "0 0% 16%",
    input: "0 0% 16%",
    ring: "0 0% 87%",
    ...sharedStatusTokens,
    radius: "0.5rem",
    shadowCard: "none",
    shadowElevated: "0 8px 24px rgba(0,0,0,0.24)",
    shadowButton: "none",
    fontFamily: sansFont,
    fontHeading: sansFont,
    letterSpacing: "0",
    textTransform: "none",
    fontWeightNormal: "400",
    fontWeightMedium: "500",
    fontWeightBold: "600",
    borderWidth: "1px",
  }),
} as const satisfies ThemePreset;
