/**
 * Guessing what an imported document IS.
 *
 * Import used to hard-code `kind: "resume"`, so every cover letter someone brought in was
 * mislabelled with no way to correct it. This module supplies a *default* for the picker —
 * never a silent decision. The user always sees the guess and can override it before the
 * document is created, which is why the confidence is exposed rather than hidden: a low
 * confidence guess is still shown, it just does not deserve a "we detected this" claim.
 */
import type { TexDocumentKind } from "@/lib/db/tex-documents";

export interface KindGuess {
  kind: TexDocumentKind;
  /**
   * `strong` when a structural signal decided it (our own macros, a salutation).
   * `weak` when only the filename hinted, or when nothing did and we fell back to resume.
   */
  confidence: "strong" | "weak";
  /** Shown next to the picker so the guess is explainable rather than magic. */
  reason: string;
}

/** Whole-word so "discovery" never reads as "cv" and "recover" never as "cover". */
function hasWord(haystack: string, word: string): boolean {
  return new RegExp(`(?:^|[^a-z])${word}(?:[^a-z]|$)`, "i").test(haystack);
}

const SALUTATION =
  /\\?\b(?:dear\s+(?:hiring|sir|madam|ms\.?|mr\.?|mx\.?|[A-Z])|to\s+whom\s+it\s+may\s+concern)/i;
const SIGN_OFF =
  /\b(?:sincerely|yours\s+(?:truly|faithfully|sincerely)|kind\s+regards|best\s+regards)\b/i;

/**
 * The order matters: structural evidence from the document body beats the filename,
 * because a file called `resume.tex` that opens "Dear Hiring Manager" is a cover letter
 * that was saved under a careless name.
 */
export function detectDocumentKind(
  source: string,
  filename?: string,
): KindGuess {
  // Our own macros are definitive — the document was generated by us and says what it is.
  if (/\\slothingPara\b/.test(source) && !/\\slothingSection\b/.test(source)) {
    return {
      kind: "cover_letter",
      confidence: "strong",
      reason: "It is built from paragraphs rather than sections.",
    };
  }
  if (/\\slothingSection\b/.test(source)) {
    return {
      kind: "resume",
      confidence: "strong",
      reason: "It is built from sections and entries.",
    };
  }

  const body = bodyOf(source);
  if (SALUTATION.test(body) || SIGN_OFF.test(body)) {
    return {
      kind: "cover_letter",
      confidence: "strong",
      reason: "It opens or closes like a letter.",
    };
  }

  const name = filename ?? "";
  if (
    hasWord(name, "cover") ||
    hasWord(name, "coverletter") ||
    /cover[-_ ]?letter/i.test(name)
  ) {
    return {
      kind: "cover_letter",
      confidence: "weak",
      reason: "The file name mentions a cover letter.",
    };
  }
  if (hasWord(name, "cv") || /curriculum[-_ ]?vitae/i.test(name)) {
    return {
      kind: "cv",
      confidence: "weak",
      reason: "The file name mentions a CV.",
    };
  }

  return {
    kind: "resume",
    confidence: "weak",
    reason: "Nothing pointed elsewhere, so this is the default.",
  };
}

/**
 * The prose between \begin{document} and \end{document}.
 *
 * A preamble routinely defines macros with names like `\coverletterheader`, and matching a
 * salutation against those produces confident nonsense. Only the body is evidence.
 */
function bodyOf(source: string): string {
  const start = source.search(/\\begin\s*\{document\}/);
  if (start === -1) return source;
  const end = source.search(/\\end\s*\{document\}/);
  return source.slice(start, end === -1 ? source.length : end);
}
